//! Manage the bundled `teapotx serve` process, config file, and log buffer.

use std::collections::VecDeque;
use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, Manager, State};
use tauri_plugin_shell::ShellExt;
use tauri_plugin_shell::process::{CommandChild, CommandEvent};

const MAX_LOG_LINES: usize = 8_000;
const CONFIG_FILE: &str = "config.toml";

/// Shared runtime for the sidecar server process.
pub struct ServerRuntime {
  child: Mutex<Option<CommandChild>>,
  logs: Mutex<VecDeque<String>>,
}

impl ServerRuntime {
  pub fn new() -> Self {
    Self {
      child: Mutex::new(None),
      logs: Mutex::new(VecDeque::with_capacity(1024)),
    }
  }

  fn push_log(&self, line: String) {
    let mut logs = self.logs.lock().expect("log mutex");
    if logs.len() >= MAX_LOG_LINES {
      logs.pop_front();
    }
    logs.push_back(line);
  }

  fn is_running(&self) -> bool {
    self.child.lock().expect("child mutex").is_some()
  }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerStatus {
  pub running: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppConfigDto {
  pub listen: String,
  /// Empty string means no API key (default).
  pub api_key: String,
}

impl Default for AppConfigDto {
  fn default() -> Self {
    Self {
      listen: "127.0.0.1:8080".into(),
      api_key: String::new(),
    }
  }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
  pub name: String,
  pub version: String,
}

fn config_dir(app: &AppHandle) -> Result<PathBuf, String> {
  let dir = app
    .path()
    .app_config_dir()
    .map_err(|e| format!("resolve app config dir: {e}"))?;
  fs::create_dir_all(&dir).map_err(|e| format!("create config dir: {e}"))?;
  Ok(dir)
}

fn config_path(app: &AppHandle) -> Result<PathBuf, String> {
  Ok(config_dir(app)?.join(CONFIG_FILE))
}

fn read_config_file(path: &PathBuf) -> AppConfigDto {
  let Ok(text) = fs::read_to_string(path) else {
    return AppConfigDto::default();
  };
  let value: toml::Value = match toml::from_str(&text) {
    Ok(v) => v,
    Err(_) => return AppConfigDto::default(),
  };
  let listen = value
    .get("listen")
    .and_then(|v| v.as_str())
    .unwrap_or("127.0.0.1:8080")
    .to_string();
  let api_key = value
    .get("api_key")
    .and_then(|v| v.as_str())
    .unwrap_or("")
    .to_string();
  AppConfigDto { listen, api_key }
}

fn write_config_file(path: &PathBuf, cfg: &AppConfigDto) -> Result<(), String> {
  let mut body = String::new();
  body.push_str("# Generated by Teapot desktop app\n");
  body.push_str(&format!("listen = {:?}\n", cfg.listen));
  if cfg.api_key.trim().is_empty() {
    body.push_str("# api_key is unset (open access on the listen address)\n");
  } else {
    body.push_str(&format!("api_key = {:?}\n", cfg.api_key.trim()));
  }
  body.push_str("include_progress = true\n");
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent).map_err(|e| format!("create config parent: {e}"))?;
  }
  fs::write(path, body).map_err(|e| format!("write config: {e}"))
}

fn append_and_emit(app: &AppHandle, state: &ServerRuntime, line: String) {
  state.push_log(line.clone());
  let _ = app.emit("teapotx-log", line);
}

#[tauri::command]
pub fn get_server_status(state: State<'_, ServerRuntime>) -> ServerStatus {
  ServerStatus {
    running: state.is_running(),
  }
}

#[tauri::command]
pub fn get_config(app: AppHandle) -> Result<AppConfigDto, String> {
  let path = config_path(&app)?;
  Ok(read_config_file(&path))
}

#[tauri::command]
pub fn save_config(app: AppHandle, config: AppConfigDto) -> Result<(), String> {
  if config.listen.trim().is_empty() {
    return Err("listen address must not be empty".into());
  }
  let path = config_path(&app)?;
  write_config_file(&path, &config)?;
  Ok(())
}

#[tauri::command]
pub fn get_logs(state: State<'_, ServerRuntime>) -> String {
  state
    .logs
    .lock()
    .expect("log mutex")
    .iter()
    .cloned()
    .collect::<Vec<_>>()
    .join("\n")
}

#[tauri::command]
pub fn clear_logs(state: State<'_, ServerRuntime>) {
  state.logs.lock().expect("log mutex").clear();
}

#[tauri::command]
pub fn get_app_info(app: AppHandle) -> AppInfo {
  let pkg = app.package_info();
  AppInfo {
    name: "Teapot".into(),
    version: pkg.version.to_string(),
  }
}

#[tauri::command]
pub async fn start_server(app: AppHandle, state: State<'_, ServerRuntime>) -> Result<(), String> {
  if state.is_running() {
    return Ok(());
  }

  let path = config_path(&app)?;
  if !path.exists() {
    write_config_file(&path, &AppConfigDto::default())?;
  }

  let path_str = path.display().to_string();
  append_and_emit(
    &app,
    &state,
    format!("[teapot] starting: teapotx serve --config {path_str}"),
  );

  let sidecar = app
    .shell()
    .sidecar("teapotx")
    .map_err(|e| format!("resolve teapotx sidecar: {e}"))?;

  let (mut rx, child) = sidecar
    .args(["serve", "--config", &path_str])
    .spawn()
    .map_err(|e| format!("spawn teapotx serve: {e}"))?;

  *state.child.lock().expect("child mutex") = Some(child);
  let _ = app.emit("teapotx-status", true);

  let app_handle = app.clone();
  tauri::async_runtime::spawn(async move {
    while let Some(event) = rx.recv().await {
      match event {
        CommandEvent::Stdout(line) => {
          let text = String::from_utf8_lossy(&line).trim_end().to_string();
          if text.is_empty() {
            continue;
          }
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), text);
          }
        }
        CommandEvent::Stderr(line) => {
          let text = String::from_utf8_lossy(&line).trim_end().to_string();
          if text.is_empty() {
            continue;
          }
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), text);
          }
        }
        CommandEvent::Error(err) => {
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), format!("[teapot] error: {err}"));
          }
        }
        CommandEvent::Terminated(payload) => {
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            *rt.child.lock().expect("child mutex") = None;
            let code = payload
              .code
              .map(|c| c.to_string())
              .unwrap_or_else(|| "signal".into());
            append_and_emit(
              &app_handle,
              rt.inner(),
              format!("[teapot] process exited ({code})"),
            );
          }
          let _ = app_handle.emit("teapotx-status", false);
          break;
        }
        _ => {}
      }
    }
  });

  Ok(())
}

#[tauri::command]
pub fn stop_server(app: AppHandle, state: State<'_, ServerRuntime>) -> Result<(), String> {
  let child = state.child.lock().expect("child mutex").take();
  if let Some(child) = child {
    child.kill().map_err(|e| format!("kill teapotx: {e}"))?;
    append_and_emit(&app, &state, "[teapot] stopped".into());
  }
  let _ = app.emit("teapotx-status", false);
  Ok(())
}
