//! Manage the bundled `teapotx serve` process, config file, and log buffer.

use std::collections::VecDeque;
use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, Manager, State};
use tauri_plugin_shell::ShellExt;
use tauri_plugin_shell::process::{CommandChild, CommandEvent};
use tokio::sync::oneshot;

use crate::auth::{self, DEFAULT_PROVIDER};
use crate::paths;
use teapot_core::paths::{AUTH_DIR_ENV, DATA_DIR_ENV, MODELS_DIR_ENV};

const MAX_LOG_LINES: usize = 8_000;

/// Shared runtime for the sidecar server process.
pub struct ServerRuntime {
  child: Mutex<Option<CommandChild>>,
  logs: Mutex<VecDeque<String>>,
  login_cancel: Mutex<Option<oneshot::Sender<()>>>,
}

impl ServerRuntime {
  pub fn new() -> Self {
    Self {
      child: Mutex::new(None),
      logs: Mutex::new(VecDeque::with_capacity(1024)),
      login_cancel: Mutex::new(None),
    }
  }

  fn push_log(&self, line: String) {
    let mut logs = self.logs.lock().expect("log mutex");
    if logs.len() >= MAX_LOG_LINES {
      logs.pop_front();
    }
    logs.push_back(line);
  }

  pub(crate) fn log(&self, app: &AppHandle, line: String) {
    append_and_emit(app, self, line);
  }

  pub(crate) fn try_begin_login(&self) -> Option<oneshot::Receiver<()>> {
    let mut slot = self.login_cancel.lock().expect("login mutex");
    if slot.is_some() {
      return None;
    }
    let (tx, rx) = oneshot::channel();
    *slot = Some(tx);
    Some(rx)
  }

  pub(crate) fn request_cancel_login(&self) -> bool {
    match self.login_cancel.lock().expect("login mutex").take() {
      Some(tx) => {
        let _ = tx.send(());
        true
      }
      None => false,
    }
  }

  pub(crate) fn end_login(&self) {
    let _ = self.login_cancel.lock().expect("login mutex").take();
  }

  pub(crate) fn is_running(&self) -> bool {
    self.child.lock().expect("child mutex").is_some()
  }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerStatus {
  pub running: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppConfigDto {
  pub listen: String,
  /// Empty string means no API key (default).
  pub api_key: String,
  /// Pinned provider id (`codex-cli`, `xai`, `antigravity`, `vertex`).
  pub provider: String,
}

impl Default for AppConfigDto {
  fn default() -> Self {
    Self {
      listen: "127.0.0.1:8080".into(),
      api_key: String::new(),
      provider: DEFAULT_PROVIDER.into(),
    }
  }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
  pub name: String,
  pub version: String,
}

fn config_path(app: &AppHandle) -> Result<PathBuf, String> {
  paths::config_path(app)
}

fn read_config_file(path: &PathBuf) -> AppConfigDto {
  let Ok(text) = fs::read_to_string(path) else {
    return AppConfigDto::default();
  };
  let value: toml::Value = match toml::from_str(&text) {
    Ok(v) => v,
    Err(_) => return AppConfigDto::default(),
  };
  let listen = value
    .get("listen")
    .and_then(|v| v.as_str())
    .unwrap_or("127.0.0.1:8080")
    .to_string();
  let api_key = value
    .get("api_key")
    .and_then(|v| v.as_str())
    .unwrap_or("")
    .to_string();
  let provider = value
    .get("provider")
    .and_then(|v| v.as_str())
    .unwrap_or(DEFAULT_PROVIDER)
    .to_string();
  AppConfigDto {
    listen,
    api_key,
    provider: normalize_provider(&provider).unwrap_or_else(|_| DEFAULT_PROVIDER.into()),
  }
}

fn normalize_provider(name: &str) -> Result<String, String> {
  Ok(auth::parse_provider(name)?.as_str().to_string())
}

fn write_config_file(path: &PathBuf, cfg: &AppConfigDto) -> Result<(), String> {
  let mut body = String::new();
  body.push_str("# Generated by Teapot desktop app\n");
  body.push_str(&format!("listen = {:?}\n", cfg.listen));
  if cfg.api_key.trim().is_empty() {
    body.push_str("# api_key is unset (open access on the listen address)\n");
  } else {
    body.push_str(&format!("api_key = {:?}\n", cfg.api_key.trim()));
  }
  body.push_str(&format!("provider = {:?}\n", cfg.provider));
  body.push_str("include_progress = true\n");
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent).map_err(|e| format!("create config parent: {e}"))?;
  }
  fs::write(path, body).map_err(|e| format!("write config: {e}"))
}

fn append_and_emit(app: &AppHandle, state: &ServerRuntime, line: String) {
  state.push_log(line.clone());
  let _ = app.emit("teapotx-log", line);
}

#[tauri::command]
pub fn get_server_status(state: State<'_, ServerRuntime>) -> ServerStatus {
  ServerStatus {
    running: state.is_running(),
  }
}

#[tauri::command]
pub fn get_config(app: AppHandle) -> Result<AppConfigDto, String> {
  let path = config_path(&app)?;
  Ok(read_config_file(&path))
}

#[tauri::command]
pub fn save_config(app: AppHandle, mut config: AppConfigDto) -> Result<(), String> {
  if config.listen.trim().is_empty() {
    return Err("listen address must not be empty".into());
  }
  if config.provider.trim().is_empty() {
    let existing = read_config_file(&config_path(&app)?);
    config.provider = existing.provider;
  }
  config.provider = normalize_provider(&config.provider)?;
  let path = config_path(&app)?;
  write_config_file(&path, &config)?;
  Ok(())
}

#[tauri::command]
pub fn set_provider(app: AppHandle, provider: String) -> Result<AppConfigDto, String> {
  let running = app.state::<ServerRuntime>().is_running();
  if running {
    return Err("stop the server before changing provider".into());
  }
  let path = config_path(&app)?;
  let mut cfg = read_config_file(&path);
  cfg.provider = normalize_provider(&provider)?;
  write_config_file(&path, &cfg)?;
  Ok(cfg)
}

#[tauri::command]
pub fn get_logs(state: State<'_, ServerRuntime>) -> String {
  state
    .logs
    .lock()
    .expect("log mutex")
    .iter()
    .cloned()
    .collect::<Vec<_>>()
    .join("\n")
}

#[tauri::command]
pub fn clear_logs(state: State<'_, ServerRuntime>) {
  state.logs.lock().expect("log mutex").clear();
}

#[tauri::command]
pub fn get_app_info(app: AppHandle) -> AppInfo {
  let pkg = app.package_info();
  AppInfo {
    name: "Teapot".into(),
    version: pkg.version.to_string(),
  }
}

#[tauri::command]
pub async fn start_server(app: AppHandle, state: State<'_, ServerRuntime>) -> Result<(), String> {
  if state.is_running() {
    return Ok(());
  }

  let path = config_path(&app)?;
  if !path.exists() {
    write_config_file(&path, &AppConfigDto::default())?;
  }

  let cfg = read_config_file(&path);
  let provider = normalize_provider(&cfg.provider)?;
  let kind = auth::parse_provider(&provider)?;
  let auth = auth::status_for(&app, kind)?;
  if !auth.installed {
    return Err(
      auth
        .install_hint
        .unwrap_or_else(|| format!("{provider} needs `{}` on PATH", auth.command)),
    );
  }
  if auth.supports_auth && !auth.authenticated {
    return Err(format!(
      "not signed in to {provider}; sign in before starting the server"
    ));
  }

  let data_dir = paths::data_local_dir(&app)?;
  let auth_dir = paths::auth_dir(&app)?;
  let models_dir = paths::models_dir(&app)?;
  fs::create_dir_all(&data_dir).map_err(|e| format!("create data local dir: {e}"))?;
  let path_str = path.display().to_string();
  append_and_emit(
    &app,
    &state,
    format!(
      "[teapot] starting: teapotx serve --config {path_str} -p {provider} ({DATA_DIR_ENV}={})",
      data_dir.display()
    ),
  );

  let sidecar = app
    .shell()
    .sidecar("teapotx")
    .map_err(|e| format!("resolve teapotx sidecar: {e}"))?;

  let path_env = teapot_core::augmented_path();
  let (mut rx, child) = sidecar
    .args(["serve", "--config", &path_str, "-p", &provider])
    .env(DATA_DIR_ENV, &data_dir)
    .env(AUTH_DIR_ENV, &auth_dir)
    .env(MODELS_DIR_ENV, &models_dir)
    .env("PATH", path_env)
    .spawn()
    .map_err(|e| format!("spawn teapotx serve: {e}"))?;

  *state.child.lock().expect("child mutex") = Some(child);
  let _ = app.emit("teapotx-status", true);

  let app_handle = app.clone();
  tauri::async_runtime::spawn(async move {
    while let Some(event) = rx.recv().await {
      match event {
        CommandEvent::Stdout(line) => {
          let text = String::from_utf8_lossy(&line).trim_end().to_string();
          if text.is_empty() {
            continue;
          }
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), text);
          }
        }
        CommandEvent::Stderr(line) => {
          let text = String::from_utf8_lossy(&line).trim_end().to_string();
          if text.is_empty() {
            continue;
          }
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), text);
          }
        }
        CommandEvent::Error(err) => {
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            append_and_emit(&app_handle, rt.inner(), format!("[teapot] error: {err}"));
          }
        }
        CommandEvent::Terminated(payload) => {
          if let Some(rt) = app_handle.try_state::<ServerRuntime>() {
            *rt.child.lock().expect("child mutex") = None;
            let code = payload
              .code
              .map(|c| c.to_string())
              .unwrap_or_else(|| "signal".into());
            append_and_emit(
              &app_handle,
              rt.inner(),
              format!("[teapot] process exited ({code})"),
            );
          }
          let _ = app_handle.emit("teapotx-status", false);
          break;
        }
        _ => {}
      }
    }
  });

  Ok(())
}

#[tauri::command]
pub fn stop_server(app: AppHandle, state: State<'_, ServerRuntime>) -> Result<(), String> {
  let child = state.child.lock().expect("child mutex").take();
  if let Some(child) = child {
    child.kill().map_err(|e| format!("kill teapotx: {e}"))?;
    append_and_emit(&app, &state, "[teapot] stopped".into());
  }
  let _ = app.emit("teapotx-status", false);
  Ok(())
}
